seo:
  site_name: BrightDeck
  title: BrightDeck Interior Design (default seo)
  description: We create contemporary interior design, help achieve functional and aesthetical-pleasing space 
  keywords: interior design 
  social_image: /images/bg-interior-kitchen.jpg
  author:
  favorite_image: 
social:
  instagram_username: 
  facebook_url:
  twitter_username:
  twitter_description:
design:
  dark-background_color: '#506d5f'
  light-background_color: '#e5ece8'
  featured_color: '#506d5f'
  text-dark_color: '#243026'
  text-white_color: 'white'
  icons_color: 'rgb(120,120,125)'